from robot_v_dinos_class import *

weapon_one = Weapon("Gatling Gun", 25)
weapon_two = Weapon("Buzzsaw", 25)
weapon_three = Weapon("Unibeam", 25)
ability_one = Weapon("Bite", 25)
ability_two = Weapon("Charging Ram", 25)
ability_three = Weapon("Tail Whip", 25)
tyranozill = Dinosaur("Tyranozill", ability_one, ability_two, ability_three)
venomous_raptor = Dinosaur("Venomous Raptor", ability_one, ability_two, ability_three)
pterosaur = Dinosaur("Pterosaur", ability_one, ability_two, ability_three)
bionic_baron = Robot("Bionic Baron", weapon_one, weapon_two, weapon_three)
megatron = Robot("Megatron", weapon_one, weapon_two, weapon_three)
juggernaut = Robot("Juggernaut", weapon_one, weapon_two, weapon_three)
battlefield = Battlefield(fleet, herd)
battlefield.run_game()
